### ISSUE TITLE
Using the Maven pom to build source code

### ISSUE THREAD

**Issue by damianoneill** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#99]
When I run the pom (I had to update the snapshot refs and move yang files into src/main/java), I get the following error 

Failed to find leafref target: /Tapi:Context/Tapi:_topology/TapiTopology:_node/TapiTopology:uuid

Full exception - 

$ mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Transport API YANG Modules 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ TapiYang ---
[INFO] Deleting /Users/doneill/projects/github/Snowmass-ONFOpenTransport/YANG/target
[INFO]
[INFO] --- yang-maven-plugin:0.8.4-SNAPSHOT:generate-sources (generate-sources) @ TapiYang ---
[INFO] yang-to-sources: Inspecting /Users/doneill/projects/github/Snowmass-ONFOpenTransport/YANG/src/main/yang
[INFO] yang-to-sources: YANG files parsed from [META-INF/yang/Tapi.yang, META-INF/yang/TapiConnectivity.yang, META-INF/yang/TapiEth.yang, META-INF/yang/TapiNotification.yang, META-INF/yang/TapiOch.yang, META-INF/yang/TapiOdu.yang, META-INF/yang/TapiPathComputation.yang, META-INF/yang/TapiTopology.yang, META-INF/yang/TapiVirtualNetwork.yang]
[INFO] yang-to-sources: Code generator instantiated from org.opendaylight.yangtools.maven.sal.api.gen.plugin.CodeGeneratorImpl
[INFO] yang-to-sources: Sources will be generated to /Users/doneill/projects/github/Snowmass-ONFOpenTransport/YANG/target/generated-sources/sal
[ERROR] yang-to-sources: Unable to generate sources with org.opendaylight.yangtools.maven.sal.api.gen.plugin.CodeGeneratorImpl generator
java.lang.IllegalArgumentException: Failed to find leafref target: /Tapi:Context/Tapi:_topology/TapiTopology:_node/TapiTopology:uuid
	at org.opendaylight.yangtools.sal.binding.yang.types.TypeProviderImpl.provideTypeForLeafref(TypeProviderImpl.java:450)
	at org.opendaylight.yangtools.sal.binding.yang.types.TypeProviderImpl.javaTypeForLeafrefOrIdentityRef(TypeProviderImpl.java:251)
	at org.opendaylight.yangtools.sal.binding.yang.types.TypeProviderImpl.javaTypeForSchemaDefinitionType(TypeProviderImpl.java:211)
	at org.opendaylight.yangtools.sal.binding.generator.impl.BindingGeneratorImpl.resolveLeafListSchemaNode(BindingGeneratorImpl.java:1590)
	at org.opendaylight.yangtools.sal.binding.generator.impl.BindingGeneratorImpl.addSchemaNodeToBuilderAsMethod(BindingGeneratorImpl.java:1135)
	at org.opendaylight.yangtools.sal.binding.generator.impl.BindingGeneratorImpl.resolveDataSchemaNodes(BindingGeneratorImpl.java:1070)
	at org.opendaylight.yangtools.sal.binding.generator.impl.BindingGeneratorImpl.groupingToGenType(BindingGeneratorImpl.java:717)
	at org.opendaylight.yangtools.sal.binding.generator.impl.BindingGeneratorImpl.groupingsToGenTypes(BindingGeneratorImpl.java:695)
	at org.opendaylight.yangtools.sal.binding.generator.impl.BindingGeneratorImpl.moduleToGenTypes(BindingGeneratorImpl.java:266)
	at org.opendaylight.yangtools.sal.binding.generator.impl.BindingGeneratorImpl.generateTypes(BindingGeneratorImpl.java:244)
	at org.opendaylight.yangtools.maven.sal.api.gen.plugin.CodeGeneratorImpl.generateSources(CodeGeneratorImpl.java:61)
	at org.opendaylight.yangtools.yang2sources.plugin.YangToSourcesProcessor.generateSourcesWithOneGenerator(YangToSourcesProcessor.java:340)
	at org.opendaylight.yangtools.yang2sources.plugin.YangToSourcesProcessor.generateSources(YangToSourcesProcessor.java:285)
	at org.opendaylight.yangtools.yang2sources.plugin.YangToSourcesProcessor.execute(YangToSourcesProcessor.java:95)
	at org.opendaylight.yangtools.yang2sources.plugin.YangToSourcesMojo.execute(YangToSourcesMojo.java:116)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] yang-to-sources: One or more code generators failed, including failed list(generatorClass=exception) {org.opendaylight.yangtools.maven.sal.api.gen.plugin.CodeGeneratorImpl=java.lang.IllegalArgumentException}
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.279 s
[INFO] Finished at: 2016-09-22T17:07:23+01:00
[INFO] Final Memory: 21M/492M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.opendaylight.yangtools:yang-maven-plugin:0.8.4-SNAPSHOT:generate-sources (generate-sources) on project TapiYang: yang-to-sources: One or more code generators failed, including failed list(generatorClass=exception) {org.opendaylight.yangtools.maven.sal.api.gen.plugin.CodeGeneratorImpl=java.lang.IllegalArgumentException} -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by RodLU** [comment]
You can change the 'Tapi:Topology:uuid' into 'Tapi:uuid' in Yang files to see if this problem still remained. I think this problem has someting to do with the module name.

**Comment by rvilalta** [comment]
If 'Tapi:Topology:uuid' into 'Tapi:uuid' then pyang complaints. Are you sure this is a possible solution?

**Comment by rvilalta** [comment]
I will need help with this. In pyang TapiTopology produces no errors. Any suggestions?

**Comment by karthik-sethuraman** [comment]
Unable to reproduce this  issues using pyang. Need more information
